### PR TITLE
fix(PrometheusTargetSyncFailure): probe support

### PR DESCRIPTION
**Pull request by georgettica**
found a CU who created a probe that isn't working

### CODE REVIEW

**Comment by simonpasquier** [comment]
/lgtm

@georgettica by any chance do you have more details about the Probe definition that triggered the alert? I assume that eventually it's a bug in the Prometheus operator that we should fix.

**Comment by georgettica** [comment]
I just monitored the issue, pinged the CR owner

**Comment by georgettica** [comment]
the problematic CR
```
apiVersion: monitoring.coreos.com/v1
kind: Probe
metadata:
  name: example
  namespace: test
spec:
  interval: 10s
  jobName: httpstat-test
  module: http_2xx
  prober:
    path: /probe
    scheme: https
    url: https://blackbox-exporter.XXX
  targets:
    staticConfig:
      relabelingConfigs:
        - replacement: test-app
          targetLabel: app
        - replacement: endpoint-name
          targetLabel: name
        - action: labeldrop
          regex: namespace
      static:
        - 'https://httpstat.us/200'
```


the problem was, that spec.prober.url is supposed to be a pure host:port definition (which is strange since it is called url)

so a correct prober declaration would be

```
  prober:
    path: /probe
    scheme: https
    url: blackbox-exporter.XXX
```

**Comment by simonpasquier** [comment]
Thanks! I've filed https://github.com/prometheus-operator/prometheus-operator/issues/4476

**Pull request merged**
