### PR TITLE
CNV-30825: add KubevirtHCOSingleStackIPv6 runboook

### PR DESCRIPTION
**Pull request by apinnick**

### CODE REVIEW

**Comment by apinnick** [comment]
@sradco @nunnatsa Can you review this PR?

**Comment by sradco** [comment]
We ate missing the "open case if you can't fix this" . Do you think its needed here?
and what about having the link to the known issue for tracking? not needed?

**Comment by apinnick** [comment]
> We ate missing the "open case if you can't fix this" . Do you think its needed here? and what about having the link to the known issue for tracking? not needed?

@sradco 
I thought about adding the "Open a case". But I asked myself, Would anyone really open a case to install CNV on a cluster on IPv4 or IPv4/IPv6 cluster?

Re: tracking bug. Not sure about that. We are not supposed to promise future features. Also, an alert is supposed to tell the user what to do now. If the alert appears, then the user knows that single stack IPv6 is not yet supported, don't you think?

**Pull request merged**
