### PR TITLE
ETCD-586: add runbook entry for etcd-ca expiration alert

### PR DESCRIPTION
**Pull request by tjungblu**
/hold

waiting for the definitive doc url

### CODE REVIEW

**Comment by tjungblu** [comment]
@DanielOsypenko what would be a good diagnosis?

**Comment by DanielOsypenko** [comment]
I am not aware of this particular alert. This is general requirement on Runbooks. It is not explicitly mentioned in description, but within comments it was given as an expected result. See story https://issues.redhat.com/browse/RHSTOR-3613
Without this chapter "Diagnosis" the automation test will fail, and bz created.

**Comment by tjungblu** [comment]
I don't even know what ODF stands for, it's for OCP etcd.

**Pull request merged**
