### PR TITLE
fixing typo in etcd failed grpc request expr

### PR DESCRIPTION
**Pull request by tjungblu**
fix for #59

### CODE REVIEW

**Comment by faxm0dem** [comment]
Thanks for fixing this !
The query is now valid, but in our case its result is an empty data set.
Whereas the old query popped up the correct hits.

**Comment by tjungblu** [comment]
@faxm0dem the old query was wrong, in a sense that the operator precedence wasn't working correctly which resulted in bogus divisions and error rates. This one works correctly and only alert once you have errors ;)

**Comment by faxm0dem** [comment]
Thanks for your answer. However, we do have alerts, evey night, and the new query returns 0 hits :man_shrugging:

**Comment by tjungblu** [comment]
@faxm0dem I don't entirely understand, which OpenShift version do you run? Do you already have the updated alert installed?

**Comment by faxm0dem** [comment]
We're running 4.10.0-0.okd-2022-07-09-073606 and no I didn't change the alert.
If I understand correctly your suggestion, there are two things:

1. The alertmanager alert query found in `/monitoring/alertrules/ALERT_ID`
2. The runbook query in the README that is being addressed in this PR

Both should be updated, and 1. has to be done manually (or wait for openshift update).

**Pull request merged**
