### PR TITLE
CNV-36964 - Updating mitigation info for VMStorageClassWarning

### PR DESCRIPTION
**Pull request by jherrman**
See https://issues.redhat.com/browse/CNV-36964

### CODE REVIEW

**Comment by sradco** [comment]
@machadovilaca what would happen with the sync automation in this case?
Do we need to replace this in the upstream runbook ?

**Comment by machadovilaca** [comment]
> @machadovilaca what would happen with the sync automation in this case? Do we need to replace this in the upstream runbook ?

we should update the upstream runbooks, or the next time we update this upstream runbook it will suggest to overwrite these changes

**Comment by sradco** [comment]
@jherrman can you please update the runbook in https://github.com/kubevirt/monitoring/blob/main/docs/runbooks/VMStorageClassWarning.md instead of opening this directly?

**Comment by jherrman** [comment]
@sradco @machadovilaca , ah, so for future reference, do I understand correctly that all updates/PR for runbook content should now be made against https://github.com/kubevirt/monitoring rather than https://github.com/openshift/runbooks ?

Cheers,
J.

**Comment by jherrman** [comment]
Anyway, here's the PR for the upstream repo: https://github.com/kubevirt/monitoring/pull/256

**Comment by jherrman** [comment]
Oops, forgot to close this PR, fixing now.

**Comment by sradco** [comment]
@jherrman Hi, What is the status of this PR?

**Comment by jherrman** [comment]
@sradco , apologies, I guess GitHub was misbehaving when I was trying to close it ~2 weeks ago. Anyhow, should be finally done now.

**Pull request closed without merging**
